export const FactionMapping: any = {
  "Aeldari - Craftworlds": "",
  "Aeldari - Drukhari": "Drukhari",
  "Aeldari - FW Corsairs": "",
  "Aeldari - Harlequins": "Harlequins",
  "Aeldari - Ynnari": "Ynnari",
  "Chaos - Chaos Knights": "",
  "Chaos - Chaos Space Marines": "",
  "Chaos - Daemons": "Daemons",
  "Chaos - Death Guard": "DeathGuard",
  "Chaos - FW Heretic Astartes": "",
  "Chaos - FW Renegade and Heretics": "",
  "Chaos - Gellerpox Infected": "",
  "Chaos - Servants of the Abyss": "",
  "Chaos - Thousand Sons": "ThousandSons",
  "Chaos - Titanicus Traitoris": "",
  Fallen: "",
  "Imperium - Adepta Sororitas": "AdeptaSororitas",
  "Imperium - Adeptus Astra Telepathica": "",
  "Imperium - Adeptus Custodes": "AdeptusCustodes",
  "Imperium - Adeptus Mechanicus": "AdeptusMechanicus",
  "Imperium - Astra Cartographica": "",
  "Imperium - Astra Militarum - Library": "",
  "Imperium - Astra Militarum": "",
  "Imperium - Black Templars": "",
  "Imperium - Blackstone Fortress": "",
  "Imperium - Blood Angels": "BloodAngels",
  "Imperium - Dark Angels": "",
  "Imperium - Deathwatch": "Deathwatch",
  "Imperium - Adeptus Astartes - Deathwatch": "Deathwatch",
  "Imperium - Elucidian Starstriders": "",
  "Imperium - FW Adeptus Astartes": "",
  "Imperium - FW Death Korps of Krieg": "",
  "Imperium - FW Elysians": "",
  "Imperium - Grey Knights": "",
  "Imperium - Imperial Fists": "",
  "Imperium - Imperial Knights": "",
  "Imperium - Inquisition": "",
  "Imperium - Iron Hands": "",
  "Imperium - Legion of the Damned": "",
  "Imperium - Officio Assassinorum": "",
  "Imperium - Raven Guard": "",
  "Imperium - Salamanders": "",
  "Imperium - Sisters of Silence": "",
  "Imperium - Space Marines": "",
  "Imperium - Space Wolves": "",
  "Imperium - Titan Legions": "",
  "Imperium - Ultramarines": "",
  "Imperium - White Scars": "",
  Necrons: "Necrons",
  Orks: "Orks",
  "T'au Empire": "",
  "Tyranids - Genestealer Cults": "GenestealerCults",
  "Tyranids - Genestealer Cults - 2022": "GenestealerCults",
  Tyranids: "Tyranids",
  "Unaligned - Monsters and Gribblies": "",
};
